pipeline {
    environment {
        jar = "demo-log4jshell-0.0.1-SNAPSHOT.jar"
        registry = "${DEFAULT_REGISTRY}"
        imageName = "snapshot/demo-log4jshell"
        namespace = "vorrarit"
        deployment = "demo-log4jshell"
        service = "demo-log4jshell-service"
        nodePort = "31301"
        port = "8080"
        majorBuild = "0"
        minorBuild = "5"
        buildVersion = "$majorBuild.$minorBuild.${BUILD_NUMBER}"
        sshInfo = "dsladm@10.212.233.40"
        pathApp = "/home/dsladm/scripts/jenkins/mid/demo-log4jshell"
        buildEnv = "snapshot"
    }
    agent any
    stages {
        stage('Build with Maven') {
            agent {
                docker {
                    image 'maven:3-jdk-11-slim'
                    args "-v ${MVN_SOURCE_VOLUME}:/root/.m2"
                    reuseNode true
                }
            }

            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"

                    pwd
                    mvn clean
                    mvn install -X -Dmaven.test.skip=true
					
                 '''
                 stash includes: "target/${env.jar}", name: 'targetfiles'
            }
        }

        stage('Build Image') {
            steps {
                script {
                    unstash 'targetfiles'
                    sh "sed -i 's|jenkins-jar|${env.jar}|g' $WORKSPACE/deployment/resources/Dockerfile"
                    a = docker.build("${env.registry}" + "/" + "${env.imageName}" + ":"+"${env.buildVersion}", "-f deployment/resources/Dockerfile .")
                    a.push()
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /root/.trivy:/root/.cache aquasec/trivy --exit-code 1 --severity CRITICAL $registry/$imageName:$buildVersion
                 '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sshagent (credentials: ['dev-ssh-key-kube'])
                {
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/deployment/resources/namespace.yaml"
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/deployment/resources/deployment.yaml"
                    sh "sed -i 's|jenkins-deployment|$deployment|g' $WORKSPACE/deployment/resources/deployment.yaml"
                    sh "sed -i 's|jenkins-port|$port|g' $WORKSPACE/deployment/resources/deployment.yaml"
                    sh "sed -i 's|image-container|$registry/$imageName:$buildVersion|g' $WORKSPACE/deployment/resources/deployment.yaml"
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-deployment|$deployment|g' $WORKSPACE/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-service|$service|g' $WORKSPACE/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-port|$port|g' $WORKSPACE/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-node-port|$nodePort|g' $WORKSPACE/deployment/resources/service.yaml"
                    sh '''
                        ssh -o StrictHostKeyChecking=no $sshInfo mkdir -p $pathApp
                        scp $WORKSPACE/deployment/resources/* $sshInfo:$pathApp
                        scp $WORKSPACE/deployment/$buildEnv/config-map.yaml $sshInfo:$pathApp
                        ssh -o StrictHostKeyChecking=no $sshInfo uname -a
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/namespace.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/config-map.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/deployment.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/service.yaml
                    '''
                }
           	}
        }
    }
}